### ISSUE TITLE
HTML5 library

### ISSUE THREAD

**Issue by GammaGames** [Beliaar/godot-yaml-asset#4] opened 2019-08-09 02:39 UTC
Would it be possible to update this asset for HTML5 exports?

**Comment by GammaGames** [comment] 2019-08-09 02:41
Oh, is this a gdnative library? If so it looks like web exports don't support gdnative godotengine/godot/issues/12243

**Comment by Beliar83** [comment] 2019-08-09 04:41
It is gdnative, yes, which means according to that issue that it seems not to be possible to update for html5.

**Comment by GammaGames** [comment] 2019-08-09 04:44
Thank you, you can close this issue if you want and I've subscribed to that thread so I can get updates there.

**Comment by GammaGames** [comment] 2020-12-11 16:33
Hmm, looks like the 3.2.4 beta might support this feature: https://github.com/godotengine/godot/pull/44076

**Comment by Beliar83** [comment] 2020-12-11 18:58
I can take a look at that when I have the time.

**Comment by otDan** [comment] 2022-02-21 00:18
so did you ever take a look?

**Comment by Beliar83** [comment] 2022-02-21 07:17
Sorry, I think I was waiting for it being in an official release and then forget. I will definitely take a look this week or weekend.

**Comment by otDan** [comment] 2022-02-22 11:54
that's good to hear, would be great to have that working

**Comment by Beliar83** [comment] 2022-02-26 14:40
This could prove to be a bit more difficult. Godot is being built with exceptions disabled for javascript, by default.
I could find a way to output yaml without using yaml-cpp methods that use exceptions, but for parsing this does not seem to be possible.

I will try to find a way, but it will probably take a bit longer than I hoped.

**Comment by otDan** [comment] 2022-02-26 16:52
hmm I see, I might need to write some hacky parser then for my project if this will take long as it's basically the only thing I am missing. but thanks for looking into this, will be waiting for the release!

**Comment by otDan** [comment] 2022-03-09 17:21
would there be any ETA on this? if you are in general looking into it.

**Comment by Beliar83** [comment] 2022-03-09 18:45
I can't say. I am looking into using a different library, which I can hopefully make to produce the same results, but I need to rewrite some things.

**Comment by Beliar83** [comment] 2022-03-14 20:32
Small update, I found a library with customizable error handling and got the basics to work with that. The rest should not take too long, though it depends on how much time I can work on this.

The new library outputs tags a bit differently than the old one (that put tags in a "<>") though, but from what I see this is more like the standard anyway.

**Comment by otDan** [comment] 2022-03-18 19:01
cool update me whenever you get more progress and know an ETA thanks :)

**Comment by Beliar83** [comment] 2022-03-28 19:01
Sorry, I forgot about the ETA, but I have finished the changes. The files in the asset library are pending approval at this moment, but you should be able to download directly from here, if you want to test it now.

**Comment by otDan** [comment] 2022-03-29 11:55
I will definitely check this out asap. Thanks!

**Comment by otDan** [comment] 2022-03-30 10:52
Hmm I seem to have an issue when exporting the html project still as it says the parser is null

**Comment by Beliar83** [comment] 2022-03-30 11:10
@otDan Did you get it from the asset library or directly from here? The new version on the asset library apparently was not yet reviewed.
For reference, the version/tag should be 0.9.3

**Comment by otDan** [comment] 2022-03-30 22:03
@Beliaar yeah I got it directly from this repo, gonna try it out more when I have some time, but yeah it seems that the instance is null for some reason

**Comment by Beliar83** [comment] 2022-04-01 06:47
@otDan Not quite sure what the problem could be. I tried with a new project and the files downloaded from here and it works. What exact message do you get?

**Comment by otDan** [comment] 2022-04-01 23:43
> @otDan Not quite sure what the problem could be. I tried with a new project and the files downloaded from here and it works. What exact message do you get?

is there a way I can contact you directly for a simpler support? I can show you off what happens when I export it out, think that would be the fastest way to show what exactly breaks

**Comment by otDan** [comment] 2022-04-02 00:31
![image](https://user-images.githubusercontent.com/59731738/161356919-dd435cec-c05b-441e-877e-ec3f1a556f17.png)
this is the error though if that's enough for you

**Comment by Beliar83** [comment] 2022-04-02 11:54
@otDan Not quite sure what I have that would make that easier.

The problem is that you need to export with gdnative support. The message "does not have a library for the current platform." is the main hint.

However there are no HTML export templates for the mono version that have gdnative support, as far as I see.
If you don't need the mono version you should download the normal version of godot and make sure to set "Export Type" to "GDNative". Otherwise you could try to compile the export templates yourself, but I would recommend against trying, as I found that extremely difficult when it involves mono.

![grafik](https://user-images.githubusercontent.com/728747/161381770-c6078efb-f202-4aed-be69-e3dd38da79d0.png)

**Comment by otDan** [comment] 2022-04-02 23:36
thank you so much! yeah I did not even realize I was using the mono version, I have versions ranging from 3.0 to 4.0 and sometimes open up the wrong one. everything works fine now, I really appreciate your work on this!

**Comment by Beliar83** [comment] 2022-04-03 06:28
Good to hear. I am closing this issue then.

**Closed as completed by Beliar83** 2022-04-03 06:28 UTC
Labels: enhancement

**Comment by Beliar83** [comment] 2022-04-03 06:29
Ah, and the version on the asset library has also been approved.

**Comment by GammaGames** [comment] 2022-04-04 15:39
Thank you for all your work on this! Gonna play with it during my lunch break, hopefully I can get an export up for a tool I made.

Edit: Worked great! I've got it hosted on gh pages, pretty handy little feature: https://gammagames.github.io/procedural-generation-ruleset/play/
